"""
Copyright 2020, University of Freiburg
Chair of Algorithms and Data Structures.
Theresa Klumpp <klumppt@cs.uni-freiburg.de>
"""

import pickle
import argparse
from flask import Flask, render_template, request, url_for  # NOQA


app = Flask(__name__)


@app.route("/")
@app.route("/home")
def home():
    return render_template("home.html", evaluation=evaluation)


if __name__ == "__main__":
    # Parse the command line arguments.
    parser = argparse.ArgumentParser(description="""Build a webapp that nicly
            presents the evaluation data.""")
    # Positional arguments
    parser.add_argument("evaluation_file", type=str, help="""Precomputed
            evaluation file as generated by 'evaluate_inverted_index.py'.""")
    # Optional arguments
    parser.add_argument("-p", "--port", type=int, default=5000, help="""Port
            for the webapp (default: %(default)s).""")
    args = parser.parse_args()
    evaluation = pickle.load(open(args.evaluation_file, "rb"))
    app.run(port=args.port, host="0.0.0.0", debug=True)
